### PR TITLE
Remove Unused Array Header

### PR DESCRIPTION
**Pull request by dmichalowicz**
With this change I was able to get CVXcanon to build on OS X. See also: https://github.com/cvxgrp/CVXcanon/issues/30

### CODE REVIEW

**Comment by richafrank** [comment]
@dmichalowicz Should we make this a PR against upstream and try to push for a new release?

**Comment by richafrank** [comment]
(👍 Your change matches my understanding.)

**Comment by dmichalowicz** [comment]
I did that here: https://github.com/cvxgrp/CVXcanon/pull/34, should I actually merge this first and then make that PR against our master version? (assuming it may not get accepted right away)

**Comment by richafrank** [comment]
Oh nice, ok. 

If we think upstream might get merged, then I'm tempted to make something like a q-master branch in our fork and have master match upstream's master. If that's not likely, then feel free to merge.

**Comment by dmichalowicz** [comment]
Ok I made https://github.com/quantopian/CVXcanon/tree/q-master with this change for any of our devs to use if need be. Going to leave this open for now to give the upstream PR a chance for a few days at least.

**Comment by dmichalowicz** [comment]
Closing this since the upstream PR merged, and this change is also available on the `q-master` branch I mentioned.

**Pull request closed without merging**
